#!/bin/bash
nt_head="XayOn.net\'s alert system"
nt_type="Message"
nt_icon="gtk-dialog-info"
nt_time=5000
cat - | {
while read k v; do
    case $k in
        TYPE) nt_type=$v;;
        ICON) nt_icon=$v;;
        CONTENT) nt_text=$v;;
        SENDER) SENDER=`printf $v | sed 's/[^a-zA-Z 0-9]//g'`;;
        TIMEOUT) nt_time=$v;;
        SUBJECT) nt_head=$v;;
    esac
done

echo "$nt_type $nt_icon $nt_text $SENDER $nt_time $nt_head"


if [ "$SENDER" == "CallSystem" ]; then
    #strip_and_call "$nt_text"
    notify-send -i "$nt_icon" -c "$nt_type" -t $nt_time -- "Calling..." "$nt_text"
    exit
fi

if [ "$SENDER" != "" ]; then
    [[ -e ~/.silent ]] && exit
    notify-send -i "$nt_icon" -c "$nt_type" -t "$nt_time" -- "$SENDER" "$nt_text"
    exit
fi


if [ "$nt_text" != "" ]; then
    printf -- $nt_text|grep "MAIL_NOTIFICATION"
    if [ $? == 0 ]; then
        nt_text=`printf -- $nt_text|sed 's/MAIL_NOTIFICATION//g'`
    notify-send -i "$nt_icon" -c "$nt_type" -t "$nt_time" -- "You have a new mail" "$nt_text"
        exit;
    fi

    echo $nt_text|while read action simbol ip tal cual log; do
        if [ "$simbol" == "-" ]; then
            if [ "$action" != "remove" ]; then
                log=`echo $log|sed 's/\/var\/log\///g'`;
                notify-send -i "$nt_icon" -c "$nt_type" -t $nt_time -- "XayOn.net's alert system" "Added $ip to $log"
            fi
        else
            notify-send -i "$nt_icon" -c "$nt_type" -t $nt_time -- "XayOn.net's alert system" "$nt_text"
        fi
    done
fi

}

