#!/bin/bash
source /etc/nanobenv.conf 2>/dev/null
source ~/.nanobenv/etc/nanobenv.conf 2>/dev/null
$wd/wizards/sync_calendars
mkdir -p ~/.nanobenv/calcurse
cp -r $wd/config/calcurse/* ~/.nanobenv/calcurse/

