#!/bin/bash
source /etc/pimshit.conf
cp -r $wd/config/goobook/* ~/.pimshit/goobook/

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && {
    # Interactive mode
    echo "This setup will configure your Google contacts user and password"
    read -p "Enter username: " username
    read -p "Enter password: " password
}

sed -i "s/$username/REPLACEUSER/g" ~/.pimshit/goobook/goobookrc
sed -i "s/$password/REPLACEPASS/g" ~/.pimshit/goobook/goobookrc
