#!/bin/bash
source /etc/nanobenv.conf 2>/dev/null
source ~/.nanobenv/etc/nanobenv.conf 2>/dev/null

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && {
    # Interactive mode
    echo "This setup will configure your Google contacts user and password"
    read -p "Enter username: " username
    read -s -p "Enter password: " password
} || {
    mkdir -p ~/.nanobenv/goobook
}
cp -r $wd/config/goobook/* ~/.nanobenv/goobook/

sed -i "s/REPLACEUSER/$username/g" ~/.nanobenv/goobook/goobookrc
sed -i "s/REPLACEPASS/$password/g" ~/.nanobenv/goobook/goobookrc
