#!/bin/bash
source /etc/pimshit.conf

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && {
    # Interactive mode
    echo "This setup will configure your GMail user and password"
    read -p "If you want to use a different provider, edit ~/.pimshit/mutt/muttrc later"
    read -p "Enter username: " username
    read -p "Enter password: " password
    read -p "Enter your real name: " realname
} || {
    mkdir ~/.pimshit/mutt/
}

cp -r $wd/config/mutt/* ~/.pimshit/mutt/

[[ $username == *@* ]] && {
    from=$username;
} || {
    from="${username}@gmail.com"
}

sed -i "s/REPLACEUSER/$username/g" ~/.pimshit/mutt/muttrc
sed -i "s/REPLACEPASS/$password/g" ~/.pimshit/mutt/muttrc
sed -i "s/REPLACEREALNAME/$realname/g" ~/.pimshit/mutt/muttrc
sed -i "s/REPLACEFROM/$from/g" ~/.pimshit/mutt/muttrc

source $wd/wizards/goobook
