#!/bin/bash
source /etc/nanobenv.conf 2>/dev/null
source ~/.nanobenv/etc/nanobenv.conf 2>/dev/null

mkdir -p ~/.nanobenv/sync_calendar/ &>/dev/null
read -p "Enter calendar urls (space separated) here: " calendar_urls
echo $calendar_urls >> ~/.nanobenv/sync_calendar/${drivers[calendar]}.conf
