#!/bin/bash
source /etc/pimshit.conf
mkdir -p ~/.pimshit/sync_calendar/ &>/dev/null
read -p "Enter calendar urls (space separated) here: " calendar_urls
echo $calendar_urls >> ~/.pimshit/sync_calendar/${drivers[calendar]}.conf
