#!/bin/bash
source /etc/nanobenv.conf

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && {
    # Interactive mode
    echo "This setup will configure weechat for bitlbee integration"
    read -p "Enter your nickname" nick
    read -s -p "Enter your bitlbee password (if you dont have one, on nex exec, issue the command /msg &bitlbee register <this_password>)"
}

cp -r $wd/config/weechat/* ~/.nanobenv/.weechat
sed -i "s/REPLACEPASS/$password/g" ~/.nanobenv/weechat/irc.conf
sed -i "s/REPLACENICKS/$nick/g" ~/.nanobenv/weechat/irc.conf
ln -s ~/.nanobenv/weechat ~/.nanobenv/.weechat/

