#!/bin/bash
source /etc/nanobenv.conf 2>/dev/null
source ~/.nanobenv/etc/nanobenv.conf 2>/dev/null
export TERM=${drivershells[${drivers[contacts]}]}
${drivercmds[${drivers[contacts]}]}"$(${wd}/sync_contacts ${drivers[contacts]})" ${@}
