#!/bin/bash
source /etc/nanobenv.conf 2>/dev/null
source ~/.nanobenv/etc/nanobenv.conf 2>/dev/null

[[ ${drivers[messaging]} == "weechat" ]] && {
    export HOME=~/.nanobenv/
}
nanobenv_call messaging
