#!/bin/bash
source /etc/pimshit.conf 2>/dev/null
source ~/.pimshit/etc/pimshit.conf 2>/dev/null


driver_=$1; shift;
{
    odir=~/.pimshit/${drivers[sync_contacts]}
    ddir=~/.pimshit/${driver_}
    ${drivercmds[${drivers[sync_contacts]}]} \
        ${driver_}_export >> ${odir}/contacts.tmp
    [[ -e ${odir}/contacts ]] && {
        diff -biw ${odir}/contacts.tmp \
            ${odir}/contacts | sed -n 's/^> //p' >> ${ddir}/addressbook
    } || {
        cat ${odir}/contacts.tmp >> ${ddir}/addressbook
    }
    mv ${odir}/contacts.tmp ${odir}/contacts
} &>~/.pimshit/sync_contacts.log

echo "$HOME/.pimshit/abook/addressbook"
