#!/bin/bash
source /etc/nanobenv.conf 2>/dev/null
source ~/.nanobenv/etc/nanobenv.conf 2>/dev/null


driver_=$1; shift;
{
    odir=~/.nanobenv/${drivers[sync_contacts]}
    ddir=~/.nanobenv/${driver_}
    ${drivercmds[${drivers[sync_contacts]}]} \
        ${driver_}_export >> ${odir}/contacts.tmp
    [[ -e ${odir}/contacts ]] && {
        diff -biw ${odir}/contacts.tmp \
            ${odir}/contacts | sed -n 's/^> //p' >> ${ddir}/addressbook
    } || {
        cat ${odir}/contacts.tmp >> ${ddir}/addressbook
    }
    mv ${odir}/contacts.tmp ${odir}/contacts
} &>~/.nanobenv/sync_contacts.log

echo "$HOME/.nanobenv/abook/addressbook"
