#!/bin/bash
source /etc/pimshit.conf
export TERM=${drivershells[tmux]}

function launch_commands(){
    shift
    for driver in ${@}; do
        tmux neww -n "${driver^}" "pimshit ${driver}"
    done
}

function get_first(){
    echo $1;
    return 0;
}

[[ $1 ]] && {
    drivers_=($(eval echo \${drivers_$1[@]}))
} || {
    drivers_=(${!drivers[@]})
}

start_="$(get_first ${drivers_[@]})";
{
    sleep 2
    launch_commands "${drivers_[@]}"
} &
tmux new -n "${start_^}" "pimshit ${start_}"
